### ISSUE TITLE
xml Schnittstelle zum Auslesen der Spielpläne

### ISSUE THREAD

**Issue by mvo5** [garnas/einrad.hockey#120]
Liebes Einradhockey.liga team. Ich würde mich über eine XML Schnittstelle zum Auslesen der Spielplan Details freuen. In erster Linie benötige ich die Paarungen. Mein Ziel ist es, die Spielpläne in https://github.com/mvo5/gamescore zu importieren.

Gamescore ist das Tool das Trier benutzt um die Zeit und Punkte auf einem externen Monitor während des Spiels zeigen und derzeit muss man die Teamnamen per Hand eingeben (was natürlich ein wenig umständlich ist :)

Ich schicke euch eine Draft PR, leider bin ich kein PHP Entwickler, daher müsst ihr ein wenig Nachsicht mit mir haben :)

Was die Frage aufwirft ob die (trivial) Funktionalität von Gamescore nicht auch was für einradhockey.liga wäre?

**Comment by garnas** [comment]
Hi,

ich finde das ist eine sehr gute Idee. Ich schaue es mir die Tage mal an.

**Comment by garnas** [comment]
Hi,

so die Xml-Schnittstelle ist jetzt online:

Bsp für das nächste Wochenende: 
https://einrad.hockey/xml/spielplan?turnier_id=1029

Auch vergangene Turniere funktionieren zum Testen, allerdings ohne Trikotfarbe:
https://einrad.hockey/xml/spielplan?turnier_id=1021

**Comment by garnas** [comment]
Theoretisch könnte Gamescore die Ergebnisse und Zeit auch direkt an einrad.hockey schicken. Dann hätte man eine Art Liveticker.

Ich würde es mir so vorstellen, dass Gamescore per Rest einen api-key, die Turnier-Id, Spiel-Id, Ergebnis, die aktuelle Spielzeit und die Periode (1. Halbzeit, 2. Halbzeit, Ende, Penalty) an einrad.hockey sendet. Im Spielplan könnte das dann dargestellt werden. 

Beispiel:
Gallier 1 : Römer 2 
 2. Halbzeit - noch 04:33 zu spielen

**Comment by mvo5** [comment]
> Hi,
> 
> so die Xml-Schnittstelle ist jetzt online:
> 
> Bsp für das nächste Wochenende: https://einrad.hockey/xml/spielplan?turnier_id=1029
> 
> Auch vergangene Turniere funktionieren zum Testen, allerdings ohne Trikotfarbe: https://einrad.hockey/xml/spielplan?turnier_id=1021

Super, vielen Dank! Das sieht klasse aus, dann schaue ich mal, dass ich am WE Zeit finde die neue Schnittstelle zu integrieren :-)

**Comment by mvo5** [comment]
> Theoretisch könnte Gamescore die Ergebnisse und Zeit auch direkt an einrad.hockey schicken. Dann hätte man eine Art Liveticker.
> 
> Ich würde es mir so vorstellen, dass Gamescore per Rest einen api-key, die Turnier-Id, Spiel-Id, Ergebnis, die aktuelle Spielzeit und die Periode (1. Halbzeit, 2. Halbzeit, Ende, Penalty) an einrad.hockey sendet. Im Spielplan könnte das dann dargestellt werden.
> 
> Beispiel: Gallier 1 : Römer 2 2. Halbzeit - noch 04:33 zu spielen

Das ist eine sehr coole Idee! Traditionell ist gamescore auf offline optimiert, aber heute hat ja wirklich jeder Mobile Daten und einen Hotspot Modus im Handy und damit könnten wir das machen. Ich denke mal ein wenig drüber nach :)

Danke nochmals!
 Michael
