### ISSUE TITLE
Blockeigene Turniere werden nach Öffnung nicht als blockfrei angegeben

### ISSUE THREAD

**Issue by Largofin** [garnas/einrad.hockey#126]
Beispiel: https://einrad.hockey/liga/turnier_details?turnier_id=1151

Das Turnier ist - wie unten stehe - zuvor ein blockeigenes Turnier gewesen, dann aber blockfrei geworden.
Eine solche Änderungen ist aber nicht in den Turnierdetails zu stehen. Der Modus beschreibt, dass Turniere nach dem Öffnen ein blockfreies Turnier sind.

**Comment by garnas** [comment]
Turniere der Art III wurden ja entfernt. In der Setzphase werden dann eh alle Ligaturnierarten gleichbehandelt

Bei Turnierart kann dann aber natürlich ein "(blockfrei)" hinzugefügt werden.

**Comment by Largofin** [comment]
Sehe hier ggfs. einen Widerspruch zum Ligamodus und bitte sonst um Korrektur:
Wird ein Turnier als blockeigen ausgeschrieben und *nicht* geöffnet (auf ABCDEF), so kann es als 4er-Turnier stattfinden. Wird ein blockeigenes Turnier geöffnet (auf ABCDEF) und es finden sich nur Teams des eigenen Blocks (sodass es eigentlich blockeigen bzw. auf zwei Blöcke beschränkt bleiben können), dann ist ein 4er-Turnier *nicht* mehr möglich.
Wie gesagt, gerne Korrektur.

Sollte ich richtg liegen, so sollte man aus meiner Sicht deutlich machen, dass ein 4er-Turnier *nicht* mehr möglich ist. Ansonsten ist das hinfällig.
