### ISSUE TITLE
Teams werden in den Turnierdetails doppelt angezeigt

### ISSUE THREAD

**Issue by Largofin** [garnas/einrad.hockey#127]
Die Teams in der Turnier Übersicht und in den Turnierdetails stimmen nicht überein.

https://einrad.hockey/liga/turnier_details?turnier_id=1152

**Comment by garnas** [comment]
Ich denke hier hat jemand bei einem Spaßturnier manuell ein Team doppelt angemeldet. Bei Spaßturnieren existiert keine Validierung, da dürfen die Ausrichter machen was sie wollen ;)
.

**Comment by Largofin** [comment]
So kann es auch gehandhabt werden. Doch auf https://einrad.hockey/liga/turniere wurden in den Modals andere Teams angezeigt als in den schlussendlichen Turnierdetails https://einrad.hockey/liga/turnier_details?turnier_id=1152 dargestellt.
Das lässt sich hier nicht mehr rekonstruieren. Vielleicht existiert das Problem trotzdem nur bei Spaßturnieren.
Aber selbst wenn, dann sollte man das ggfs. beheben. Sonst melden sich vielleicht Teams nicht mehr an, weil im Modal eine volle Liste dargestellt wird, aber in den Turnierdetails noch Plätze sind.
