### ISSUE TITLE
authentication error beim forum

### ISSUE THREAD

**Issue by Largofin** [garnas/einrad.hockey#129]
Es scheint ein Problem bei der Authentication im Forum zu geben. Es können keine Posts und auch keine Suchen abgesetzt werden.
Liegt das Problem im CAPTCHA?

Theoretisch liegt auch eine neue Version des Forums vor und ggfs. löst der Patch das Problem. Oder eine config ist falsch.

**Comment by garnas** [comment]
Forum wurde erstmal deaktiviert, mal schauen ob es nochmal aktiviert wird.
