### ISSUE TITLE
XML schnittstelle für Spielpläne zeigt manchmal 404

### ISSUE THREAD

**Issue by mvo5** [garnas/einrad.hockey#131]
Ich möchte morgen die (nicht mehr ganz) neue Schnittstelle der Spielpläne in XML nutzen für das Turnier in Trier.

Dabei habe ich gemerkt, dass nicht für alle Pläne die XML Daten vorhanden zu sein scheinen. Z.b.:

https://einrad.hockey/liga/turnier_details?turnier_id=1197
https://einrad.hockey/xml/spielplan?turnier_id=1197 git ein 404

aber
https://einrad.hockey/liga/turnier_details?turnier_id=1198
https://einrad.hockey/xml/spielplan?turnier_id=1198 ist prima

Oder
https://einrad.hockey/liga/turnier_details?turnier_id=1159
https://einrad.hockey/xml/spielplan?turnier_id=1159 ist 404

Über Hilfe würde ich mich sehr freuen :)

**Comment by garnas** [comment]
Hi,

das liegt daran, dass für die 404er Turniere keine Spielpläne in der DB vorhanden sind. Das kann daran liegen:

1. das Turnier hat noch keinen Spielplan erstellt bekommen hat (ist nicht in der Spielplanphase)
2. das Turnier hat einen PDF oder xlsx Spielplan hinterlegt bekommen (das ist bei nicht Jeder-Gegen-Jeder Turnieren der Fall)

**Comment by mvo5** [comment]
Hallo, vielen Dank! Das macht Sinn, ich denke es ist (2), i.e. der Spielplan wurde von Hand erstellt..
