### ISSUE TITLE
Anzahl der gespielten Turniere in Statistik ist falsch

### ISSUE THREAD

**Issue by Largofin** [garnas/einrad.hockey#133]
In der Anzahl der Turniere wird im Moment ein Spaßturnier mit ausgewertet, da es den Status / die Phase "ergebnis" hat. Deshalb sollte die Abfrage um die art erweitert werden.

```
SELECT turniere_liga.*, turniere_details.*, teams_liga.teamname 
FROM turniere_liga 
INNER JOIN turniere_details 
ON turniere_liga.turnier_id = turniere_details.turnier_id
INNER JOIN teams_liga
ON teams_liga.team_id = turniere_liga.ausrichter
WHERE phase = 'ergebnis'
AND saison = ?
AND (art LIKE "I" OR art LIKE "II" OR art LIKE "III")
ORDER BY turniere_liga.datum " . ($asc ? "asc" : "desc");
```

https://github.com/garnas/einrad.hockey/blob/4ce6f416baa0c80dbcf9ef17cdb2b15e9f3320bb/classes/nturnier.class.php#L508-L520

**Comment by Largofin** [comment]
Edit: Falsche Codestelle referenziert.

**Comment by Largofin** [comment]
Für das ausweisen der eigentlichen Anzahl ist auch

```
SELECT COUNT(*) as anzahl
FROM turniere_liga 
WHERE phase = 'ergebnis'
AND (art LIKE "I" OR art LIKE "II" OR art LIKE "III")
AND saison = ?
```

ausreichend.

**Comment by garnas** [comment]
Hi,

habe es gefixt - danke
