### ISSUE TITLE
Ergebnistabelle bei 3er Turnieren nicht korrekt

### ISSUE THREAD

**Issue by Largofin** [garnas/einrad.hockey#137]
Bei 3er-Turnieren wird die Ergebnis-Tabelle nicht richtig angegeben.
Hier werden scheinbar nur die Spiele aus der Hin- oder Rückrunde berückstichtigt.

https://einrad.hockey/liga/spielplan?turnier_id=1254

**Comment by garnas** [comment]
Stimmt, problem ist, dass in der Turniertabelle die team_ids als key genommen werden. Daher wird nur ein Spiel aus Hin/Rückrunde betrachtet. Ich habe die Tabellen jetzt erstmal ausgeblendet für den 3er Spielplan.

Sollte der 3er Spielplan irgendwann mal regelmäßig gespielt werden, können wir die Funktionalität hierfür hinzufügen ;)
