### ISSUE TITLE
km-challenge

### ISSUE THREAD

**Issue by Largofin** [garnas/einrad.hockey#21]
- [x] Die mobile public-Seite kann nicht angezeigt werden
- [x] Nach Formulareingabe fehlt ein Reload / Die
- [x] Die km-Challenge wird nicht in der Sidebar im Teamcenter angezeigt (mobil)
- [x] Die Ergebnis-Tabelle im Teamcenter wird nicht angezeigt (mobil)
- [x] Ggfs. Überschrift / Unterschrift im Teamcenter für die beiden Hauptzahlen hinzufügen

Reopen:
- [x] Challenge in der Schnellübersicht (linke Seite auf der Hauptseite) hinzufügen
- [x] Aus Link auf der public-Page einen Button machen
- [x] Teams die Möglichkeit geben, die eigenen Einträge zu löschen / bearbeiten
- [x] Ersten bis Dritten Platz hervorheben (Abgesetzte Farben für den Zeilenhintergrund)
- [x] Texte ändern
- [x] Ergebnisse sollen nicht im Voraus eingetragen werden können

**Comment by garnas** [comment]
Habe die Bugs soweit behoben. Außerdem habe ich noch:

Ein Confirm fürs Form fürs Eintragen der Kilometer hinzugefügt.
Fürs Datum-Input ein min max und value gesetzt.
Einen Link zum Eintragen auf der öffentlichen Seite erstellt.

@Largofin wenn dir etwas nicht passt, kannst du es auch wieder ändern ;) Nur die Hinweise beim Confirm für den Datenschutz sind denke ich wichtig.

**Comment by Largofin** [comment]
- [ ] Challenge in der Schnellübersicht (linke Seite auf der Hauptseite) hinzufügen

**Comment by Largofin** [comment]
Es sind nochmal Anmerkungen aus dem ÖA gekommen. Diese habe ich oben hinzugefügt bzw. werden dann noch ergänzt.
