### ISSUE TITLE
Erweiterung des Kontaktcenters

### ISSUE THREAD

**Issue by Largofin** [garnas/einrad.hockey#33]
Bisher kann über da Kontaktcenter eine Mal an folgende Gruppen geschrieben werden:
- Turnierteilnehmer
- von Hand gewählte Teams
- alle Teams (Rundmail)

Mein Vorschlag ist letztere Gruppe aufzuteilen. Stattdessen sollten folgende Gruppen verwendet werden:
- Turnierteilnehmer (wie zuvor)
- von Hand gewählte Teams (wie zuvor)
- **alle Ligavertreter (neu)**
- **alle Mail-Adressen (neu)**

Die Teams haben die Möglichkeit viel mehr als eine Mail-Adresse in ihren Daten anzugeben. Das war mir selber nicht bekannt. 
Diese Mail Adressen werden im Moment angeschrieben, wenn eine Mail an alle verschickt wird. Dabei wird davon ausgegangen, dass es sich um die LV handelt.
Stattdessen könnten die Rundschreiben künftig nicht nur an die LV adressiert sein, sondern auch "normale" Spieler. Ich denke dadurch würde die Möglichkeit geschaffen werden, dass Newsletter verschickt werden.

Eine wichtige Frage die dabei geklärt werden muss:
**Gibt es Mails, die ausschließlich an den LV verschickt werden sollten?**

**Comment by Largofin** [comment]
Man kann dieses Thema auch noch erweitern:
Wie wäre es, wenn die unterschiedlichen Mail-Typen unterschieden werden (Newsletter, Rundschreiben, Bot-Mails) und geziehlt angegeben werden kann, welche dieser Typen an welche Adresse geschickt werden sollen?

Ich finde man kann deutlich besser zwischen den Mails differenzieren als es bisher geschieht und kann dies auch zu einer geziehlten, bedarfsgerechten Kommunikation verwenden!

**Comment by garnas** [comment]
Es gibt keine Unterscheidung, welche der Mails zum Ligavertreter gehören. Sollten wir einen Verein gründen, dann brauchen wir wohl eh Wohnort etc vom Ligavertreter. Hier müssen wir schauen, dass wir eine gute Datenbankstruktur finden. 

Mein Vorschlag: Ein weiteres Feld, dass es sich um die Mail des Ligavertreters handelt im Teamdaten-Ändern-Formular mit einer Spalte Ligavertreter enum("ja","nein"). Die Adress- / Telefondaten des Ligavertreters werden dann in einer neuen Tabelle getrennt gespeichert.

**Comment by garnas** [comment]
Ich habe schon häufiger überlegt das Kontaktcenter zu verbessern oder neu zu schreiben, es ist zur zeit nicht perfekt programmiert.

**Comment by garnas** [comment]
Da der Fall bisher noch nie auftrat und würde er erstmal nur unnötige Komplexität in die Seite bringen. Wenn klar ist, wie ein Verein strukturiert ist, kann man es wieder aufnehmen.
