### ISSUE TITLE
Individuelle Spielzeit für jedes Turnier

### ISSUE THREAD

**Issue by Largofin** [garnas/einrad.hockey#41]
Der Ligaausschuss soll schnell einen Spielplan dahingehend anpassen, dass dieser "vom Standard" abweichen kann. Dazu folgende Gedanken:

- In der Datebank sind die Standardspielzeiten vermerkt
- Im Ligacenter wird deshalb bei Turnier ein Haken angezeigt, der den Standard bestätigt
- Wenn dieser Haken entfernt wird, können Einstellungen vorgenommen werden
- Diese Einstellungen werden unter der TurnierID in der Datenbank hinterlegt
- Bei Turnieraufruf muss also küftig geprüft werden, ob eine andere Spielzeit hinterlegt ist. Wenn nicht, dann muss auf den Standard zurückgegriffen werden
- Sollte der Haken wieder gesetzt werden, dann wird der Eintrag gelöscht. (?)

Der letzte Punkt muss nochmal geklärt werden

Gegenvorschläge gerne gesehen! :)

**Comment by garnas** [comment]
Wäre es nicht einfacher weitere Spielpläne mit unterschiedlichen Spielzeiten zu erstellen? Ansonsten würde ich die Spielzeit und Pausenzeit komplett in der neuen Tabellen speichern und in der Spielplantabelle rausnehmen. 

Sonst wird es nur ungewöhnlich verworren. Außerdem sparen wir uns Code, da wir uns die Abfrage nach der Standardspielzeit sparen.

**Comment by Largofin** [comment]
Ich schaue mir einmal Lösungen an. Ich versuche auch das ein wenig auzuteilen, sodass wir das gut abfangen können.
Dennoch würde ich nicht die Liste der "Standard"-Spielzeiten erweitern. Ggfs. werden ja noch andere Zeiten gebraucht, wie zB 2x10 min.

**Comment by garnas** [comment]
Spielzeit kann jetzt für Turniere variabel verändert werden.
