### ISSUE TITLE
Signatur des LA bei Versand über das Kontaktcenter

### ISSUE THREAD

**Issue by Largofin** [garnas/einrad.hockey#42]
Bisher werden die Mails aus dem Kontaktcenter mit einem Hinweis versehen, dass sie von dort verschickt werden -> Sollte so bleiben
Wenn der LA eine Mail verschickt, dann sollte sich dort die Signatur wiederfinden

**Comment by garnas** [comment]
Die Signatur kann gleich in die Textarea (if ($ligacenter)..). eingefügt werden. Über die Klasse Ligaleitung bekommt man gleich die tagesaktuelle Ligaausschusszusammensetzung.

**Comment by garnas** [comment]
Wurde erstellt.
