### ISSUE TITLE
Abstimmungs-Tool für LA-Wahl

### ISSUE THREAD

**Issue by Largofin** [garnas/einrad.hockey#43]
Hier kann sicherlich auf die Programmierung der Abstimmung 01/2021 zurückgegriffen werden.
**Bei der Erstellung ist auf den Modus zu achten**

**Comment by garnas** [comment]
Ich würde hiermit erst anfangen, wenn es sicher eine LA-Wahl geben wird. Die Abstimmungsklasse ist gut Dokumentiert und dürfte schnell angepasst sein.
