### ISSUE TITLE
Finalturniere Allgemein / Finalturniere auf der Turnierübersicht anzeigen

### ISSUE THREAD

**Issue by Largofin** [garnas/einrad.hockey#58]

**Comment by Largofin** [comment]
Eine Liste ist im entsprechenden Branch eingsetzt.

Gemacht werden muss noch:
- [ ] Darstellung der Liste
- [ ] Darstellung bei fehlendem Turnier
- [ ] Refactoring?

**Comment by Largofin** [comment]
Mir ist bei der Bearbeitung aufgefallen, dass die Einrichtung der Finalturniere - aus meiner Sicht - nicht optimal ist.
- Alle haben die gleiche Turnierart
- Es muss ein Ausrichter eingesetzt werden
- Es wird automatisch ein Block eingesetzt
- Für ein mögliches zweitägiges Finalturnier kann nur ein Datum eingesetzt werden

**Comment by garnas** [comment]
**Art**
Das alle Finalturniere die Turnierart final haben ist denke ich sinnvoll, da es nun mal ihre Art ist. Wichtig ist es nur für die Darstellung in der Turnierliste und für den Ligabot. Unterscheidungen würde ich über den Turniertitel vornehmen - technisch sehe ich gerade keine Notwendigkeit für unterschiedliche Arten.

**Block/Ausrichter**
Ausrichter und Block sollten wir in der Datenbank nullable machen. Die Turniere haben dann keinen Block mehr. Bei der Erstellung des Turnierobjektes müsste man dann noch anpassungen vornehmen. Spaßturniere sollten auch keinen Block haben, das kann man dann gleich mit einbauen.

**Mehrtägig**
Die beste Lösung ist aus meiner Sicht aus dem Turnier zwei oder mehr Unter-Turniere zu erstellen. Die Vorrunde und Hauptrunde haben ja eh unterschiedliche Spielpläne und unterschiedliche Hallen, oder?

**Comment by Largofin** [comment]
Art
Es gibt auf jeden Fall für das Finale und das B- und C-Finale Unterschiede. Alleine das Finale ist mit 12 Mannschaften anders. Außer man legt dafür mehrere Turniere an. Finde eine Lösung über den Turniernamen (wie ich ihn jetzt eingebaut habe) nicht gut. Das ist aus meiner Sicht sehr fehleranfällig, alleine schon wenn ein Typo entsteht.
Vielleicht sollte man die Abschlussturniere auch einfach über ein anderes Formular lösen?

Mehrtägig
Eigentlich sind für das Finale alle Turniere 6er-Turniere. Das entscheidende ist nur die Übernahme der "doppelten" Spiele. Das ginge aber auch händisch, dass der Ausrichter es machen kann. Mir wäre wichtig, dass es alles in einer Seite gelöst ist und ich nicht zwischen mehreren Turnieren wechseln muss.
Unterschiedliche Hallen nicht unbedingt. Wenn dann nur unterschiedliche Spielfelder.
Es braucht eine Lösung, die flexibel ist. Die Spiepläne müssen im schlimmsten Falle in jedem Jahr angepasst werden. Auch hier der Gedanke: Vielleicht sollte man die Finalturniere einmal vollkommen unabhängig von den Ligaturnieren betrachten.

**Comment by Largofin** [comment]
Für die Turnierübersicht habe ich ein PR gesetzt. #59
Würde das vielleicht technisch trennen wollen. Dann können wir die Liste schon einsetzen, auch wenn wir noch etwas im Hintergrund klären müssen.

**Comment by garnas** [comment]
> ` Finde eine Lösung über den Turniernamen (wie ich ihn jetzt eingebaut habe) nicht gut. Das ist aus meiner Sicht sehr fehleranfällig, alleine schon wenn ein Typo entsteht.`

Dafür ist das auch nicht gedacht. Wo brauchst du denn eine technische Unterscheidung zwischen den Turnieren? Wir handlen die Finalturniere ja manuell

**Comment by Largofin** [comment]
Technische Unterscheidung ist für die Liste sinnvoll. So kann ich sie in der richtigen Reihenfolge darstellen. Ansonsten müssen sie in einer "zufälligen" Reihenfolge (Datum oder ID) dargestellt werden.
Zudem sehe ich den Vorteil, dass für die drei unterschiedlichen Turnierarten (Art 1: Finale, Art 2: B- und C-Finale, Art 3: Saisonschlusstunier) bessere Möglichkeiten zur teilweisen automatisierung bestehen.

**Comment by Largofin** [comment]
Darüber hinaus mein Gedanke, ob nicht ein Parent für Turniere erstellt werden könnte, in dem sich die Turnierindikatoren befinden, die für Finals und Liagturnier benötigt werden. Für die weiteren Informationen der Liagturniere könnte ein Child erstellt werden.

**Comment by Largofin** [comment]
Mit dem PR #59 wurde ein Blocktyp erstellt. Dadurch hat sich das offene Problem hier erledigt.
