### ISSUE TITLE
Kopierfunktion für vergangene Turniere

### ISSUE THREAD

**Issue by Largofin** [garnas/einrad.hockey#81]

**Comment by N226335735** [comment]
Quick setup — if you’ve done this kind of thing before
or	
HTTPS
SSH
	
Get started by [creating a new file](https://github.com/N226335735/-/new/main) or [uploading an existing file](https://github.com/N226335735/-/upload). We recommend every repository include a [README](https://github.com/N226335735/-/new/main?readme=1), [LICENSE](https://github.com/N226335735/-/new/main?filename=LICENSE.md), and [.gitignore](https://github.com/N226335735/-/new/main?filename=.gitignore).
…or create a new repository on the command line
 echo "# -" >> README.md
git init
git add README.md
git commit -m "first commit"
git branch -M main
git remote add origin https://github.com/N226335735/-.git
git push -u origin main
…or push an existing repository from the command line
 git remote add origin https://github.com/N226335735/-.git
git branch -M main
git push -u origin main
…or import code from another repository
You can initialize this repository with code from a Subversion, Mercurial, or TFS project.

[Import code](https://github.com/N226335735/-/import)[](https://github.com/)
 ProTip! Use the URL for this page when adding GitHub as a remote.
© 2022 GitHub, Inc.
[Terms](https://docs.github.com/en/github/site-policy/github-terms-of-service)
[Privacy](https://docs.github.com/en/github/site-policy/github-privacy-statement)
[Security](https://github.com/security)
[Status](https://www.githubstatus.com/)
[Docs](https://docs.github.com/)
