### ISSUE TITLE
Spielpläne anpassen funktioniert nicht

### ISSUE THREAD

**Issue by garnas** [garnas/einrad.hockey#89]
4er Spielplan mit 2x12 min --> "Es existiert bereits ein manueller Spielplan

musste den default 4er auf 2x12 umstellen

**Comment by Largofin** [comment]
Wenn ich es richtig überblicke, dann wird sowieso im Moment nur vom Standard ausgegangen und ein anderen Spielplan kann nur manuell hochgeladen werden.
Sollte es nicht das Ziel sein, dass die Spielzeit geändert werden kann, ohne einen manuellen Spielplan zu veröffentlichen?
